"""Tests for user-facing interactive FCI result reports."""

from __future__ import annotations

from pathlib import Path

from fci_engine import Endpoint, FCIConfig, FCIResult, PAG, render_interactive_report
from fci_engine.diagnostics import CITraceEvent, OrientationEvent


def _result_with_directed_edge() -> FCIResult:
    graph = PAG(["X", "Y"])
    graph.add_edge("X", "Y", Endpoint.TAIL, Endpoint.ARROW)
    return FCIResult(
        graph=graph,
        sepsets={},
        ci_test_count=2,
        cache_hits=0,
        elapsed_time=0.01,
        config=FCIConfig(alpha=0.01),
        orientation_trace=[
            OrientationEvent(
                rule="R1",
                edge=("X", "Y"),
                oriented_endpoint="X",
                before=Endpoint.CIRCLE,
                after=Endpoint.TAIL,
                before_edge="X o-> Y",
                after_edge="X --> Y",
                reason="avoid new unshielded collider A-X-Y",
            )
        ],
        ci_test_trace=[
            CITraceEvent(
                query_index=1,
                x="X",
                y="Y",
                cond_set=(),
                independent=False,
                p_value=0.001,
                statistic=3.2,
                method="oracle",
                n_samples=100,
                cache_hit=False,
            )
        ],
    )


def test_result_renders_user_interactive_report() -> None:
    result = _result_with_directed_edge()

    html = result.to_interactive_report(title="My FCI Report")

    assert "My FCI Report" in html
    assert "data-endpoint-meaning=" in html
    assert "data-reasoning=" in html
    assert "X --&gt; Y" in html
    assert "Rule R1 oriented a tail" in html
    assert "No separating set was recorded" in html
    assert "edge-modal-backdrop" in html
    assert "not generated by a language model" in html
    assert "endpoint-legend" in html
    assert "class='edge-row'" in html
    assert "data-edge-id='edge-x-y'" in html
    assert "var firstEdge = document.querySelector" in html


def test_result_saves_user_interactive_report(tmp_path: Path) -> None:
    output = tmp_path / "fci_report.html"

    _result_with_directed_edge().save_interactive_report(output)

    html = output.read_text(encoding="utf-8")
    assert "<!doctype html>" in html
    assert "Interactive PAG report" in html
    assert "Click any edge" in html


def test_render_interactive_report_export_matches_result_method() -> None:
    result = _result_with_directed_edge()

    assert render_interactive_report(result) == result.to_interactive_report()


def test_report_edge_table_and_svg_share_click_metadata() -> None:
    html = _result_with_directed_edge().to_interactive_report()

    assert html.count("data-edge-id='edge-x-y'") == 2
    assert 'document.querySelectorAll(".graph-edge, .edge-row")' in html
    assert "markSelected(edgeNode)" in html
